<<<<<<< HEAD
markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Stardust"
markdown: rdiscount

author: "Azeril"
atom-baseurl: "http://stardust.azeril.me"
disqus: "Azeril"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
=======
# Site settings
title: Stardust
email: azeril@live.cn
description: > # this means to ignore newlines until "baseurl:"
  Love me less, but love me for a long

baseurl: "" # the subpath of your site, e.g. /blog/
url: "stardust.azeril.me" # the base hostname & protocol for your site
twitter_username: Azeril_lapland
github_username:  Azeril
>>>>>>> a169eb668a87c34a617b0d33bd3ab1478081e6be

